dbMagias = [{
    circulo: 1,
    nome: "Abençoar Alimentos",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Alimento para 1 criatura",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 1,
    nome: "Acalmar Animal",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 animal",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Adaga Mental",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Alarme",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "undefined",
    duracao: "1 dia",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Amedrontar",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 animal ou humanoide de ND 2 ou menor",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 1,
    nome: "Área Escorregadia",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Quadrado de 3m ou 1 objeto",
    duracao: "Cena",
    escola: "Convocação",
},
{
    circulo: 1,
    nome: "Arma Espiritual",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Convocação",
},
{
    circulo: 1,
    nome: "Arma Mágica",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 arma",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 1,
    nome: "Armadura Arcana",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Armamento da Natureza",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 arma",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 1,
    nome: "Aviso",
    execucao: "Movimento",
    alcance: "Longo",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Advinhação",
},
{
    circulo: 1,
    nome: "Bênção",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Criaturas escolhidas",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Caminhos da Natureza",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 arma",
    duracao: "Cena",
    escola: "Convocação",
},
{
    circulo: 1,
    nome: "Comando",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 humanoide",
    duracao: "1 rodada",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Compreensão",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura ou texto",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 1,
    nome: "Concentração de Combate",
    execucao: "Livre",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "1 rodada",
    escola: "Advinhação",
},
{
    circulo: 1,
    nome: "Conjurar Monstro",
    execucao: "Completa",
    alcance: "Curto",
    alvo: "1 criatura conjurada",
    duracao: "Sustentada",
    escola: "Convocação",
},
{
    circulo: 1,
    nome: "Consagrar",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "undefined",
    duracao: "1 dia",
    escola: "Evocação",
},
{
    circulo: 1,
    nome: "Controlar Plantas",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "undefined",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 1,
    nome: "Criar Elementos",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Elemento escolhido",
    duracao: "Instantânea",
    escola: "Convocação",
},
{
    circulo: 1,
    nome: "Criar Ilusão",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Ilusão que se estende a até 4 cubos de 1,5m",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 1,
    nome: "Curar Ferimentos",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 1,
    nome: "Despedaçar",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 critura ou objeto mundano pequeno",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 1,
    nome: "Detectar Ameaças",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Esfera de 9m de raio",
    duracao: "Instantânea",
    escola: "Advinhação",
},
{
    circulo: 1,
    nome: "Disfarce Ilusório",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 1,
    nome: "Enfeitiçar",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 humanoide",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Escudo da Fé",
    execucao: "Reação",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "1 turno",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Escuridão",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 objeto",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 1,
    nome: "Explosão de Chamas",
    execucao: "Padrão",
    alcance: "6m",
    alvo: "undefined",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 1,
    nome: "Hipnotismo",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Criaturas escolhidas de ND 2 ou menor",
    duracao: "1d4 rodadas",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Imagem Espelhada",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 1,
    nome: "Infligir Ferimentos",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Necromancia",
},
{
    circulo: 1,
    nome: "Leque Cromático",
    execucao: "Padrão",
    alcance: "4,5m",
    alvo: "undefined",
    duracao: "Instantânea",
    escola: "Ilusão",
},
{
    circulo: 1,
    nome: "Luz",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 objeto",
    duracao: "Cena",
    escola: "Evocação",
},
{
    circulo: 1,
    nome: "Névoa",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "undefined",
    duracao: "Cena",
    escola: "Convocação",
},
{
    circulo: 1,
    nome: "Orientação",
    execucao: "Movimentação",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 1,
    nome: "Perdição",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Criaturas escolhidas",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 1,
    nome: "Primor Atlético",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 1,
    nome: "Profanar",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "undefined",
    duracao: "1 dia",
    escola: "Necromancia",
},
{
    circulo: 1,
    nome: "Proteção Divina",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Queda Suave",
    execucao: "Reação",
    alcance: "Curto",
    alvo: "1 criatura ou objeto com até 200kg",
    duracao: "Até chegar ao solo ou cena, o que vier primeiro",
    escola: "Transmutação",
},
{
    circulo: 1,
    nome: "Raio do Enfraquecimento",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 1,
    nome: "Resistência a Energia",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Santuário",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Seta Infalível de Talude",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Até 2 criaturas",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 1,
    nome: "Sono",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura de ND 2 ou menor",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Suporte Ambiental",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "1 dia",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Teia",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "undefined",
    duracao: "Cena",
    escola: "Convocação",
},
{
    circulo: 1,
    nome: "Toque Chocante",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 1,
    nome: "Tranca Arcana",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 objeto Grande ou menor",
    duracao: "Permanente",
    escola: "Abjuração",
},
{
    circulo: 1,
    nome: "Tranquilidade",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 animal ou humanoide",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 1,
    nome: "Transmutar Objetos",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "Matéria-prima, como madeeira, rochas, ossos",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 1,
    nome: "Visão Mística",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "Você",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 1,
    nome: "Vitalidade Fantasma",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Instantânea",
    escola: "Necromancia",
},
{
    circulo: 2,
    nome: "Augúrio",
    execucao: "Completa",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Instantânea",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Sussuros Insanos",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 humanoide",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 2,
    nome: "Campo de Força",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 2,
    nome: "Dissipar Magia",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Abjuração",
},
{
    circulo: 2,
    nome: "Refúgio",
    execucao: "Completa",
    alcance: "Curto",
    alvo: "Domo com 6m de raio",
    duracao: "1 dia",
    escola: "Abjuração",
},
{
    circulo: 2,
    nome: "Runa de Proteção",
    execucao: "Completa",
    alcance: "Toque",
    alvo: "1 objeto ou passagem de até 6m de largura",
    duracao: "Permanente ou até descarregar",
    escola: "Abjuração",
},
{
    circulo: 2,
    nome: "Ligação Telepática",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "2 criaturas voluntárias",
    duracao: "1 dia",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Localização",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Círculo com 90m de raio",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Mapear",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "Superfície ou objeto plano",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Amarras Etéreas",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Convocação",
},
{
    circulo: 2,
    nome: "Montaria Arcana",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "",
    duracao: "1 dia",
    escola: "Convocação",
},
{
    circulo: 2,
    nome: "Salto Dimensional",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Você",
    duracao: "Instantânea",
    escola: "Convocação",
},
{
    circulo: 2,
    nome: "Servos Invisíveis",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "Criaturas Conjuradas",
    duracao: "1 cena",
    escola: "Convocação",
},
{
    circulo: 2,
    nome: "Desespero Esmagador",
    execucao: "Padrão",
    alcance: "6m",
    alvo: "Cone",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 2,
    nome: "Marca da Obediência",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 2,
    nome: "Bola de Fogo",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Esfera com 6m de raio",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Flecha Ácida",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura ou objeto",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Relâmpago",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Linha",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Sopro das Uivantes",
    execucao: "Padrão",
    alcance: "6m",
    alvo: "Cone",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Aparência Perfeita",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 2,
    nome: "Camuflagem Ilusória",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 2,
    nome: "Esculpir Sons",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura ou objeto",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 2,
    nome: "Invisibilidade",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Ilusão",
},
{
    circulo: 2,
    nome: "Conjurar Mortos-Vivos",
    execucao: "Completa",
    alcance: "Curto",
    alvo: "6 mortos-vivos",
    duracao: "Sustentada",
    escola: "Necromancia",
},
{
    circulo: 2,
    nome: "Crânio Voador de Vladislav",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Necromancia",
},
{
    circulo: 2,
    nome: "Toque Vampírico",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Necromancia",
},
{
    circulo: 2,
    nome: "Alterar Tamanho",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 objeto",
    duracao: "1 dia",
    escola: "Transmutação",
},
{
    circulo: 2,
    nome: "Metamorfose",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 2,
    nome: "Velocidade",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 2,
    nome: "Círculo da Justiça",
    execucao: "Completa",
    alcance: "Curto",
    alvo: "Cubo com 9m de lado",
    duracao: "1 dia",
    escola: "Abjuração",
},
{
    circulo: 2,
    nome: "Vestimenta da Fé",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 traje, armadura ou escudo",
    duracao: "1 dia",
    escola: "Abjuração",
},
{
    circulo: 2,
    nome: "Condição",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Até 5 criaturas",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Globo da Verdade de Gwen",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Mente Divina",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Voz Divina",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 2,
    nome: "Enxame de Pestes",
    execucao: "Completa",
    alcance: "Médio",
    alvo: "1 enxame Médio (quadrado de 1,5m)",
    duracao: "Sustentada",
    escola: "Convocação",
},
{
    circulo: 2,
    nome: "Soco de Arsenal",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Convocação",
},
{
    circulo: 2,
    nome: "Aliado Animal",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 animal prestativo",
    duracao: "1 dia",
    escola: "Encantamento",
},
{
    circulo: 2,
    nome: "Oração",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Todas as criaturas (veja texto)",
    duracao: "Sustentada",
    escola: "Encantamento",
},
{
    circulo: 2,
    nome: "Controlar Fogo",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Ver texto",
    duracao: "Cena",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Purificação",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Raio Solar",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Linha",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Tempestade Divina",
    execucao: "Completa",
    alcance: "Longo",
    alvo: "Cilindro com 9m de raio",
    duracao: "Cena",
    escola: "Evocação",
},
{
    circulo: 2,
    nome: "Silêncio",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Esfera com 6m de raio",
    duracao: "Sustentada",
    escola: "Ilusão",
},
{
    circulo: 2,
    nome: "Miasma Mefítico",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Nuvem com 6m de raio",
    duracao: "Instantânea",
    escola: "Necromancia",
},
{
    circulo: 2,
    nome: "Rogar Maldição",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Sustentada",
    escola: "Necromancia",
},
{
    circulo: 2,
    nome: "Controlar Madeira",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 objeto de madeira grande ou menor",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 2,
    nome: "Físico Divino",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 3,
    nome: "Âncora Dimensional",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura ou objeto",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 3,
    nome: "Dificultar Detecção",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura ou objeto",
    duracao: "1 dia",
    escola: "Abjuração",
},
{
    circulo: 3,
    nome: "Globo de Invulnerabilidade",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Sustentada",
    escola: "Abjuração",
},
{
    circulo: 3,
    nome: "Contato Extraplanar",
    execucao: "Completa",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "1 dia",
    escola: "Advinhação",
},
{
    circulo: 3,
    nome: "Lendas e Histórias",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura, objeto ou local",
    duracao: "Sustentada",
    escola: "Advinhação",
},
{
    circulo: 3,
    nome: "Vidência",
    execucao: "Completa",
    alcance: "Ilimitado",
    alvo: "1 criatura",
    duracao: "Sustentada",
    escola: "Advinhação",
},
{
    circulo: 3,
    nome: "Convocação Instantânea",
    execucao: "Padrão",
    alcance: "Ilimitado",
    alvo: "1 objeto de até 5kg",
    duracao: "Instantânea",
    escola: "Convocação",
},
{
    circulo: 3,
    nome: "Enxame Rubro de Ichabod",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Quadrado de 3m",
    duracao: "Sustentada",
    escola: "Convocação",
},
{
    circulo: 3,
    nome: "Teletransporte",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "Até 5 criaturas voluntárias",
    duracao: "Instantânea",
    escola: "Convocação",
},
{
    circulo: 3,
    nome: "Imobilizar",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 humanoide ou animal",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 3,
    nome: "Selo de Mana",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 3,
    nome: "Erupção Glacial",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Quadrado de 6m de lado",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 3,
    nome: "Lança Ígnea de Aleph",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 3,
    nome: "Muralha Elemental",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "",
    duracao: "Cena",
    escola: "Evocação",
},
{
    circulo: 3,
    nome: "Ilusão Lacerante",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 3,
    nome: "Manto de Sombras",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Sustentada",
    escola: "Ilusão",
},
{
    circulo: 3,
    nome: "Miragem",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "Cubo de até 90m de lado",
    duracao: "1 dia",
    escola: "Ilusão",
},
{
    circulo: 3,
    nome: "Ferver Sangue",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Sustentada",
    escola: "Necromancia",
},
{
    circulo: 3,
    nome: "Tentáculos de Trevas",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Círculo com 6m de raio",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 3,
    nome: "Pele de Pedra",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 3,
    nome: "Telecinesia",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Veja o texto",
    duracao: "Sustentada ou Intantânea",
    escola: "Transmutação",
},
{
    circulo: 3,
    nome: "Transformação de Guerra",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Sustentada",
    escola: "Transmutação",
},
{
    circulo: 3,
    nome: "Voo",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 3,
    nome: "Banimento",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Abjuração",
},
{
    circulo: 3,
    nome: "Proteção contra Magia",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 3,
    nome: "Comunhão com a Natureza",
    execucao: "Completa",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "1 dia",
    escola: "Advinhação",
},
{
    circulo: 3,
    nome: "Servo Divino",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "",
    duracao: "Cena ou até descarregar",
    escola: "Convocação",
},
{
    circulo: 3,
    nome: "Viagem Arbórea",
    execucao: "Completa",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Convocação",
},
{
    circulo: 3,
    nome: "Despertar Consciência",
    execucao: "Completa",
    alcance: "Toque",
    alvo: "1 animal ou planta",
    duracao: "1 dia",
    escola: "Encantamento",
},
{
    circulo: 3,
    nome: "Heroísmo",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Encantamento",
},
{
    circulo: 3,
    nome: "Missão Divina",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "1 semana ou até descarregar",
    escola: "Encantamento",
},
{
    circulo: 3,
    nome: "Coluna de Chamas",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "Cilindo com 3m de raio e 30km de altura",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 3,
    nome: "Dispersar as Trevas",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Esfera de 6m de raio",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 3,
    nome: "Sopro da Salvação",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Cone de 9m",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 3,
    nome: "Anular a Luz",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Área de 6m de raio",
    duracao: "Ver texto",
    escola: "Necromancia",
},
{
    circulo: 3,
    nome: "Poeira da Podridão",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Nuvem com 6m de raio",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 3,
    nome: "Servo Morto-Vivo",
    execucao: "Completa",
    alcance: "Toque",
    alvo: "1 cadáver",
    duracao: "Instantânea",
    escola: "Necromancia",
},
{
    circulo: 3,
    nome: "Controlar Água",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "Esfera com 30m de raio",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 3,
    nome: "Controlar Terra",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "9 cubos com 1,5 metros de lado",
    duracao: "Instantânea",
    escola: "Transmutação",
},
{
    circulo: 3,
    nome: "Potência Divina",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Sustentada",
    escola: "Transmutação",
},
{
    circulo: 4,
    nome: "Campo Antimagia",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Sustentada",
    escola: "Abjuração",
},
{
    circulo: 4,
    nome: "Libertação",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 4,
    nome: "Sonho",
    execucao: "10 minutos",
    alcance: "Ilimitado",
    alvo: "1 criatura viva",
    duracao: "Veja o texto",
    escola: "Advinhação",
},
{
    circulo: 4,
    nome: "Visão da Verdade",
    execucao: "Movimento",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 4,
    nome: "Conjurar Elemental",
    execucao: "Completa",
    alcance: "Médio",
    alvo: "",
    duracao: "Sustentada",
    escola: "Convocação",
},
{
    circulo: 4,
    nome: "Mão Poderosa de Talude",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "",
    duracao: "Sustentada",
    escola: "Convocação",
},
{
    circulo: 4,
    nome: "Viagem Planar",
    execucao: "Completa",
    alcance: "Toque",
    alvo: "Pessoal",
    duracao: "Instantânea",
    escola: "Convocação",
},
{
    circulo: 4,
    nome: "Alterar Memória",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Encantamento",
},
{
    circulo: 4,
    nome: "Marionete",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura",
    duracao: "Sustentada",
    escola: "Encantamento",
},
{
    circulo: 4,
    nome: "Raio Polar",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 4,
    nome: "Relâmpago Flamejante de Reynard",
    execucao: "Duas rodadas",
    alcance: "Médio",
    alvo: "",
    duracao: "Sustentada",
    escola: "Evocação",
},
{
    circulo: 4,
    nome: "Talho Invisível de Edauros",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Cone",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 4,
    nome: "Duplicata Ilusória",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 4,
    nome: "Explosão Caleidoscópica",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Esfera de 6m",
    duracao: "Instantânea",
    escola: "Ilusão",
},
{
    circulo: 4,
    nome: "Assassino Fantasmagórico",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "1 criatura",
    duracao: "Cena, até ser descarregada",
    escola: "Necromancia",
},
{
    circulo: 4,
    nome: "Muralha de Ossos",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 4,
    nome: "Animar Objetos",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Até 8 objetos Minúsculos ou Pequenos, 4 objetos Médios, 2 objetos Grandes ou 1 objeto Enorme",
    duracao: "Cena",
    escola: "Transmutação",
},
{
    circulo: 4,
    nome: "Controlar a Gravidade",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Cubo de 12m de lado",
    duracao: "Sustentada",
    escola: "Transmutação",
},
{
    circulo: 4,
    nome: "Desintegrar",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "1 criatura ou objeto",
    duracao: "Instantânea",
    escola: "Transmutação",
},
{
    circulo: 4,
    nome: "Forma Etérea",
    execucao: "Completa",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Sustentada",
    escola: "Transmutação",
},
{
    circulo: 4,
    nome: "Cúpula de Repulsão",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 4,
    nome: "Premonição",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Cena",
    escola: "Advinhação",
},
{
    circulo: 4,
    nome: "Guardião Divino",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "",
    duracao: "Cena ou até ser descarregado",
    escola: "Convocação",
},
{
    circulo: 4,
    nome: "Conceder Milagre",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Até ser descarregada",
    escola: "Encantamento",
},
{
    circulo: 4,
    nome: "Círculo da Restauração",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Círculo de 3m de raio",
    duracao: "5 rodadas",
    escola: "Evocação",
},
{
    circulo: 4,
    nome: "Cólera de Azgher",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Esfera com 6m de raio",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 4,
    nome: "Manto do Cruzado",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Sustentada",
    escola: "Evocação",
},
{
    circulo: 4,
    nome: "Terremoto",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "Dispersão com 30m de raio",
    duracao: "1 rodada",
    escola: "Evocação",
},
{
    circulo: 4,
    nome: "Ligação Sombria",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "1 criatura",
    duracao: "1 dia",
    escola: "Necromancia",
},
{
    circulo: 4,
    nome: "Controlar o Clima",
    execucao: "Completa",
    alcance: "2km",
    alvo: "Círculo com 2km de raio",
    duracao: "4d12 horas",
    escola: "Transmutação",
},
{
    circulo: 5,
    nome: "Aura Divina",
    execucao: "Padrão",
    alcance: "Pessoal",
    alvo: "Emanação de 9m de raio",
    duracao: "Cena",
    escola: "Abjuração",
},
{
    circulo: 5,
    nome: "Invulnerabilidade",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Abjuração",
},
{
    circulo: 5,
    nome: "Lágrimas de Wynna",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Abjuração",
},
{
    circulo: 5,
    nome: "Projetar Consciência",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Advinhação",
},
{
    circulo: 5,
    nome: "Buraco Negro",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Convocação",
},
{
    circulo: 5,
    nome: "Intervenção Divina",
    execucao: "Completa",
    alcance: "Veja o texto",
    alvo: "Veja o texto",
    duracao: "Veja o texto",
    escola: "Convocação",
},
{
    circulo: 5,
    nome: "Palavra Primordial",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Encantamento",
},
{
    circulo: 5,
    nome: "Fúria do Panteão",
    execucao: "Completa",
    alcance: "Longo",
    alvo: "Nuvem de tempestade com 90m de lado",
    duracao: "Sustentada",
    escola: "Evocação",
},
{
    circulo: 5,
    nome: "Segunda Chance",
    execucao: "Padrão",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 5,
    nome: "Reanimação Impura",
    execucao: "Completa",
    alcance: "Toque",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Necromancia",
},
{
    circulo: 5,
    nome: "Roubar a Alma",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Necromancia",
},
{
    circulo: 5,
    nome: "Toque da Morte",
    execucao: "",
    alcance: "",
    alvo: "",
    duracao: "",
    escola: "Necromancia",
},
{
    circulo: 5,
    nome: "Aprisionamento",
    execucao: "Completa",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Permanente",
    escola: "Abjuração",
},
{
    circulo: 5,
    nome: "Engenho de Mana",
    execucao: "padrão",
    alcance: "Médio",
    alvo: "Disco de Energia com 1,5m",
    duracao: "Sustentada",
    escola: "Abjuração",
},
{
    circulo: 5,
    nome: "Alterar Destino",
    execucao: "Reação",
    alcance: "Pessoal",
    alvo: "Você",
    duracao: "Instantânea",
    escola: "Advinhação",
},
{
    circulo: 5,
    nome: "Chuva de Meteoros",
    execucao: "Completa",
    alcance: "Longo",
    alvo: "Explosão com 9m de raio",
    duracao: "Instantânea",
    escola: "Convocação",
},
{
    circulo: 5,
    nome: "Semiplano",
    execucao: "Completa",
    alcance: "Curto",
    alvo: "",
    duracao: "1 dia",
    escola: "Convocação",
},
{
    circulo: 5,
    nome: "Legião",
    execucao: "Padrão",
    alcance: "Médio",
    alvo: "Até 10 criaturas na área",
    duracao: "Sustentada",
    escola: "Encantamento",
},
{
    circulo: 5,
    nome: "Possessão",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "1 criatura",
    duracao: "1 dia",
    escola: "Encantamento",
},
{
    circulo: 5,
    nome: "Barragem Elemental de Vectorius",
    execucao: "Padrão",
    alcance: "Longo",
    alvo: "4 esferas elementais",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 5,
    nome: "Deflagração de Mana",
    execucao: "Completa",
    alcance: "Pessoal",
    alvo: "Explosão de 15m de raio",
    duracao: "",
    escola: "Evocação",
},
{
    circulo: 5,
    nome: "Mata-Dragão",
    execucao: "Duas rodadas",
    alcance: "Pessoal",
    alvo: "Cone de 30m",
    duracao: "Instantânea",
    escola: "Evocação",
},
{
    circulo: 5,
    nome: "Réquiem",
    execucao: "Completa",
    alcance: "Curto",
    alvo: "Criaturas escolhidas",
    duracao: "Sustentada",
    escola: "Ilusão",
},
{
    circulo: 5,
    nome: "Sombra Assassina",
    execucao: "Padrãp",
    alcance: "Curto",
    alvo: "1 criatura",
    duracao: "Cena",
    escola: "Ilusão",
},
{
    circulo: 5,
    nome: "Controlar o Tempo",
    execucao: "Padrão",
    alcance: "Curto",
    alvo: "Veja o texto",
    duracao: "Veja o texto",
    escola: "Transmutação",
},
{
    circulo: 5,
    nome: "Desejo",
    execucao: "Completa",
    alcance: "Veja o texto",
    alvo: "Veja o texto",
    duracao: "Veja o texto",
    escola: "Transmutação",
},
];